version: '3.1'

services:
  node-everdade:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always  
    env_file:
      - .env
    networks:
      - fact_check_crawler_everdade-net
    ports:
      - 80:80

networks:
  fact_check_crawler_everdade-net:
    external: true
